{# ============================================================
   table.sql — Full-refresh materialization for SCOPE Delta tables

   Generates a complete SCOPE script that:
     1. Creates a Delta table (if not exists)
     2. Sets table properties (compression, etc.)
     3. Reads SS source files via FileSet + Extractors.SStream()
     4. Inserts the transformed data
   ============================================================ #}

{% materialization table, adapter='scope' %}
    {%- set identifier = model['alias'] -%}
    {%- set old_relation = adapter.get_relation(database=database, schema=schema, identifier=identifier) -%}
    {%- set target_relation = api.Relation.create(
        database=database, schema=schema, identifier=identifier, type='table'
    ) -%}

    {# -- Build the script config from model config + credentials -- #}
    {%- set model_config = config.get('model_config', {}) -%}
    {%- set delta_location = config.get('delta_location', '') -%}
    {%- set ss_source_path = config.get('ss_source_path', '') -%}
    {%- set partition_by = config.get('partition_by', none) -%}
    {%- set scope_settings = config.get('scope_settings', {}) -%}
    {%- set au = config.get('au', none) -%}
    {%- set priority = config.get('priority', none) -%}
    {%- set scope_columns = config.get('scope_columns', []) -%}
    {%- set feature_previews = config.get('scope_feature_previews', 'EnableDeltaTableDynamicInsert:on') -%}

    {# -- Generate the SCOPE script -- #}
    {%- set scope_script = scope__build_full_refresh_script(
        identifier,
        delta_location,
        ss_source_path,
        partition_by,
        scope_settings,
        scope_columns,
        feature_previews,
        sql
    ) -%}

    {{ log("Submitting SCOPE full-refresh job for " ~ identifier, info=True) }}

    {%- call statement('main') -%}
        {{ scope_script }}
    {%- endcall -%}

    {{ return({'relations': [target_relation]}) }}
{% endmaterialization %}


{# ============================================================
   Macro: build the full-refresh SCOPE script as a string
   ============================================================ #}
{% macro scope__build_full_refresh_script(
    table_name,
    delta_location,
    ss_source_path,
    partition_by,
    scope_settings,
    scope_columns,
    feature_previews,
    model_sql
) %}

{# -- Header -- #}
// ============================================================
// Generated by dbt-scope adapter
// Model: {{ table_name }}
// Strategy: full-refresh
// ============================================================

SET @@FeaturePreviews = "{{ feature_previews }}";

#DECLARE @deltaPath string = "{{ delta_location }}";
#DECLARE @ssBase string = "{{ ss_source_path }}";

{# -- CREATE TABLE IF NOT EXISTS -- #}
CREATE TABLE IF NOT EXISTS @target (
{%- for col in scope_columns %}
    {{ col.name }} {{ col.type }}{{ "," if not loop.last }}
{%- endfor %}
)
{%- if partition_by %}
PARTITIONED BY ({{ partition_by }})
{%- endif %}
LOCATION @deltaPath
OPTIONS (LAYOUT = DELTA);

{# -- ALTER TABLE SET TBLPROPERTIES (declarative) -- #}
{%- if scope_settings %}
ALTER TABLE @target SET TBLPROPERTIES (
{%- for key, value in scope_settings.items() %}
    "{{ key }}" = {{ scope__quote_property(value) }}{{ "," if not loop.last }}
{%- endfor %}
);
{%- endif %}

{# -- EXTRACT from SS files -- #}
@data =
    EXTRACT
{%- for col in scope_columns %}
{%-   if partition_by is none or col.name != partition_by %}
        {{ col.name }} : {{ col.type }},
{%-   endif %}
{%- endfor %}
        _date : DateTime,
        _serial : int,
        _source_file = FILE.URI()
    FROM @ssBase + "/{_date:yyyy}/{_date:MM}/{_date:dd}/{_date:yyyy}{_date:MM}{_date:dd}_{*}_{_serial}.ss"
    USING Extractors.SStream();

{# -- User's transformation + INSERT -- #}
@batch_data =
    {{ model_sql }};

INSERT INTO @target
SELECT * FROM @batch_data;

{% endmacro %}


{# -- Helper: quote a TBLPROPERTIES value -- #}
{% macro scope__quote_property(value) %}
{%- if value is string -%}
"{{ value }}"
{%- else -%}
{{ value }}
{%- endif -%}
{% endmacro %}
